[project]
name = "brain-cmb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "user", email = "a03440@tmu.edu.tw" }
]
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.7",
    "nibabel>=5.3.2",
    "pandas>=2.3.3",
    "pipelinecore",
    "pydicom>=2.4.3",
    "pydicom-seg>=0.4.1",
    "python-dotenv>=1.2.1",
    "pyyaml==6.0",
    "tqdm>=4.67.1",
    "typing-extensions>=4.15.0",
]

[project.scripts]
brain-cmb = "brain_cmb:main"

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
pipelinecore = { path = "../pipelinecore/dist/pipelinecore-0.1.8-py3-none-any.whl" }
